name: Django project AWS CI/CD. Copy repo to the remote, rebuild and spin up app container

on:
  push:
    branches: [ "main" ]

env:
  REMOTE_HOST: 13.51.239.74
  SSH_USER: ubuntu

permissions:
  contents: read
  id-token: write

jobs:
  push_n_run_prod:
    runs-on: ubuntu-latest

    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3
        
      - name: Configure SSH
        env:
          SSH_HOST: ${{ env.REMOTE_HOST }}
          SSH_USER: ${{ env.REMOTE_USER }}
          SSH_KEY: ${{ secrets.SSH_KEY }} 
        
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/github-actions-key
          chmod 600 ~/.ssh/github-actions-key
          cat >>~/.ssh/config <<END
          Host ec2
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/github-actions-key
            StrictHostKeyChecking no
          END

          
#       - name: Push repo to the remote
#         run: |
#           ssh ec2 'rm -r /home/ubuntu/ec2p1/*'
#           scp -r $(pwd)/* ec2:/home/ubuntu/ec2p1
          
      - name: Rebuild container and run
        run:  ssh ec2 'docker-compose -f /home/ubuntu/ec2p1/docker-compose.prod.yml up -d --build'
