name: Django project AWS CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
#  build:

  deploy:
    needs: [ build ]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Generate deployment package
        working-directory: .
        run:
          zip -r deploy.zip . -x '*.git*'